### ISSUE TITLE
Source Control died somehow

### ISSUE THREAD

**Issue by ivanednor98** [VSCodium/vscodium#1038]
Today I discovered that version control began to visually duplicate the repositories in my workspace and any action with git ends with the error ""
`> git rev-parse --git-dir
Opening repository for path='/home/work/projects/***' failed; ex=Error: Extension 'vscode.git' CANNOT use API proposal: scmValidation.
Its package.json#enabledApiProposals-property declares: [] but NOT scmValidation.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api vscode.git`

I switched to VSCodium a few months ago so haven't used VSCode since.

I've not found anything about "enabledApiProposals" error in documentation.

Unfortunately I haven't steps to reproduce

 - OS: Ubuntu 20.04
 - Architecture x64
 - Version 1.65.2, 1.66.0
![Untitled2](https://user-images.githubusercontent.com/103031176/162182493-956ec83e-8697-4375-a20e-e4a7ff20bd19.png)
![Untitled3](https://user-images.githubusercontent.com/103031176/162182515-246e4a31-b48e-4fc2-8834-3eccaf7140fa.png)

**Comment by istvnurbn** [comment]
I have the same issue on macOS and reported it under [#1037](https://github.com/VSCodium/vscodium/issues/1037)

**Comment by mariusrugan** [comment]
Hi
thanks for reporting,
macOS latest too, 

can't corroborate with upgrade (i've tried installing 1 version before), same behaviour.
vs-code works (downstream project from Microsoft)

```
Validating found git in: /usr/local/bin/git
Using git 2.35.1 from /usr/local/bin/git
> git rev-parse --git-dir
Opening repository for path='/Users/XYZ' failed; ex=Error: Extension 'vscode.git' CANNOT use API proposal: scmValidation.
Its package.json#enabledApiProposals-property declares: [] but NOT scmValidation.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api vscode.git
```

**Comment by daiyam** [comment]
The api have changed in `v1.66`. Today, I will look into it.

**Comment by daiyam** [comment]
I wasn't able to reproduce the issue but the upcoming `1.66.1` will have the missing extensions properties (#1040). So I think it should solve the issue. Please report if the `1.66.1` (when available) is fixing the issue or not. Thx

**Comment by mariusrugan** [comment]
Thanks for looking into it, is there any nightly build we can download ?

**Comment by daiyam** [comment]
The `1.66.1` will be out in few hours

**Comment by daiyam** [comment]
@mariusrugan @ivanednor98 Can you test with the new version? Thx

**Comment by istvnurbn** [comment]
@daiyam it seems like 1.66.1 has not solved the issue:

`Validating found git in: /opt/homebrew/bin/git
Using git 2.35.1 from /opt/homebrew/bin/git
> git rev-parse --git-dir
Opening repository for path='/Users/istvnurbn/REDACTED' failed; ex=Error: Extension 'vscode.git' CANNOT use API proposal: scmValidation.
Its package.json#enabledApiProposals-property declares: [] but NOT scmValidation.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api vscode.git`

**Comment by daiyam** [comment]
Can you check if the built-in git extension is `v1.0.0`? Here a related issue on https://github.com/microsoft/vscode/issues/139705

**Comment by mariusrugan** [comment]
Hi

Same thing here, 

i uninstalled vscodium from brew, took the dmg install 1.66.1, (clean install)
 
![Screenshot 2022-04-08 at 10 02 32](https://user-images.githubusercontent.com/143987/162392729-7da88281-c83d-4ad4-911f-11ac9f515e25.png)

screenshot from its first run, same behaviour as described initially,
i open a folder which is a git repo, the source control entry duplicates, infinitely. A file changed in the repo is not picked up as modified. (in git)

**Comment by mariusrugan** [comment]
The build-in extension for the above 1.66.1 is:

![Screenshot 2022-04-08 at 11 07 44](https://user-images.githubusercontent.com/143987/162404040-5e1af19a-ae37-4cac-910c-365b914dbfaa.png)

**Comment by mariusrugan** [comment]
I downgraded VSCodium all the way to Version: 1.64.2
seems the git built-in extension is pulled as "latest" release, it'ssame version,


![Screenshot 2022-04-08 at 11 13 09](https://user-images.githubusercontent.com/143987/162405202-8d2512a2-69cc-4143-b25c-acab185faa4e.png)

and seems the same errors

**Comment by daiyam** [comment]
@mariusrugan Ok, it's the wrong extension (it's from OpenVSX). Please uninstall it then restart VSCodium. If the git extension if please reinstall VSCodium (maybe from the dmg?). 

**The correct version should be `v1.0.0`** 

![Screen Shot 2022-04-08 at 11 15 54 AM](https://user-images.githubusercontent.com/587742/162405616-2edbb56f-1f4f-42af-b1af-eb2ac564c750.png)
(no built-in in the name, no download count, no rating)

**Comment by mariusrugan** [comment]
@daiyam thanks,
i didn't install any extension, as i how can i install the 1.0.0 ?
i cleaned up on each re-install (the above versions) everything, app dependencies, local dependencies.

**Comment by mariusrugan** [comment]
hold a bit, i didn't clean ~/.vscode-oss every time.

**Comment by mariusrugan** [comment]
just App and ~/Library/App Support/VSCodium

**Comment by daiyam** [comment]
@mariusrugan  Now, is VSCodium working as it should?

**Comment by mariusrugan** [comment]
the issue is not longer there, git works ok, thanks for your help @daiyam.

@istvnurbn maybe can confirm by disabling or deleting only the extension in `~/.vscode-oss/extensions` or a complete cleanup (remove the ~/.vscode-oss)

**Comment by mariusrugan** [comment]
i can reproduce the behaviour,
 
i've installed via brew, 

```
brew install --cask vscodium
==> Downloading https://github.com/VSCodium/vscodium/releases/download/1.66.0/VSCodium.x64.1.66.0.dmg
==> Installing Cask vscodium
==> Moving App 'VSCodium.app' to '/Applications/VSCodium.app'
==> Linking Binary 'codium' to '/usr/local/bin/codium'
🍺  vscodium was successfully installed!
```

and git didn't work,
and the git extension was the one listed before, 1.6.23.
removed only that one and restart, git built in is back to 1.0.0

**Comment by istvnurbn** [comment]
Hi All,

Managed to solve this. I have the latest version (1.66.1) installed with `brew` and after removing `vscode.git-1.62.3` and `vscode.git-base-1.64.0-next.68976705968` from `~/.vscode-oss/extensions` everything started to work as it should.

You can close this issue I guess.

Thanks @mariusrugan and @daiyam !

**Comment by daiyam** [comment]
@mariusrugan Thanks for the update.

**Comment by daiyam** [comment]
@ivanednor98 Can you check if by removing `vscode.git-*` in `~/.vscode-oss/extensions`, it is resolving your issue?

**Comment by ivanednor98** [comment]
@daiyam
yes, if delete ~/.vscode-oss/extensions/vscode.git-* and use VSCodium 1.66.1, the issue is solved.
thank you all for your help!

**Comment by daiyam** [comment]
If found the main issue, VSCodium is updating the built-in extensions with extensions found on open-vsx.org when I think it shouldn't do that.
@mariusrugan It isn't due to brew because I have the same behaviour with the `.dmg`

**Comment by mariusrugan** [comment]
thanks a lot for support & your work

**Comment by cryham** [comment]
So, I have this issue happening since recently on Debian 11, using
```
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-13T00:16:29.523Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.10.0-13-amd64
```
I now have to delete `vscode.git-1.62.3 ` from `~/.vscode-oss/extensions` every time before I start.
This doesn't seem to be fixed for me.

**Comment by daiyam** [comment]
@cryham openvsx will soon issue a complete fix. But, while waiting, I will add a patch to fix the issue in the next release.

**Comment by Ovidiu-S** [comment]
Any updates, please ? 
Deleting files on every restart is quite annoying

**Comment by Haribo112** [comment]
I also have this issue. Removing the files and restarting VSCodium has no effect, the files are recreated automatically and Git is unusable.

**Comment by daiyam** [comment]
The next release will be out this Thursday and that issue will resolved there.

**Comment by Haribo112** [comment]
Okay, thanks. I'll switch to Atom for now.

**Comment by REALERvolker1** [comment]
awesome. Can't wait.

**Comment by daiyam** [comment]
@Haribo112 You can use `v1.65` since only `1.66` has the issue.

**Comment by REALERvolker1** [comment]
> @Haribo112 You can use `v1.65` since only `1.66` has the issue.
Git base `v1.64.0-next.68976705968` and Git `v1.62.3` have this issue. Updating or removing built-in extensions is unfortunately disabled.

**Comment by daiyam** [comment]
`v1.67` is out and is fixing the issue.

**Comment by AutumnRivers** [comment]
> `v1.67` is out and is fixing the issue.

Are there any extra steps we should do after installing `1.67`? I'm currently on that version and still experiencing this issue.
![Screenshot 2022-05-08 111035](https://user-images.githubusercontent.com/26543607/167302712-e6698d9e-820e-4e35-b6fe-a2d608d27f8e.png)

**Comment by daiyam** [comment]
@AutumnRivers Yes, you should at least remove the git extension with `rm ~/.vscode-oss/extensions/vscode.git-*`.
The best would be to remove all extensions by deleting the `~/.vscode-oss` directory.

**Comment by AutumnRivers** [comment]
Yep, that fixed it! Thank you very much!
