### ISSUE TITLE
Flatpak: Invisible window on Wayland, but second launch works

### ISSUE THREAD

**Issue by edisondotme** [VSCodium/vscodium#2328]
**Describe the bug**
When launching VSCodium installed via Flatpak on a Linux Wayland session, the first application window that opens is completely invisible or transparent. The window frame is selectable in the desktop environment's overview/taskbar, and it seems to be interactive (responds to clicks if you guess where UI elements are), but the content area is not rendered.

If a second VSCodium window is launched (while the first invisible one is still running) using the same flatpak run command, this second window displays correctly and is fully usable.

Launching from the terminal shows warnings about unrecognized options being passed to Electron/Chromium on both the first (invisible) and second (visible) launch attempts.

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**

1. Use a Linux system running a Wayland desktop session.
2. Ensure VSCodium is installed via Flatpak (com.vscodium.codium from Flathub).
3. Open a terminal and run flatpak `run com.vscodium.codium`
4. Observe: The application appears to start (icon in taskbar/dock), but the window content is invisible. Note the terminal warnings (see Additional Context below).
5. While the first invisible instance is running, open another terminal (or use the same one) and run flatpak run com.vscodium.codium again.
6. Observe: This second window appears and renders correctly.

**Expected behavior**
The first VSCodium window launched via Flatpak should render correctly with its UI visible immediately upon launch.

**Screenshots**

![Image](https://github.com/user-attachments/assets/c8d6bd5d-79f9-40d8-a488-dbaba53805aa)

**Desktop (please complete the following information):**
 - OS: Zorin OS 17.3
 - Architecture $ uname -a
`Linux XXX 6.8.0-57-generic #59~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Mar 19 17:07:41 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

 - Version 

![Image](https://github.com/user-attachments/assets/3d5290ef-4f9d-4216-b5d3-9fce42df7ecf)

 - App Manager Flatpak
 - Sandboxed Flatpak

**Comment by privacymatters1** [comment]
I got a similar or the same problem. I use TuxedoOS (Plasma KDE) with a wayland session and since today its not possible to use VSCodium. I can see in the taskbar and systemmonitor that VSCodium has started, but no window is visible. I also installed it via Flatpak and I get errors like @edisondotme by launching it in from a terminal. 

Warning: 'enable-wayland-ime' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'wayland-text-input-version' is not in the list of known options, but still passed to Electron/Chromium.

has somebody an idea how to fix it?

**Comment by xXSalamanderXx** [comment]
Exact same issue but mine is worse, it doesn't even open, just instantly crashes. Using Flatpak VSCodium, Wayland, Zorin OS 17.3

Edit: Just tried the .deb version and that runs perfectly. Seems to be related to the flatpak VSCodium

**Comment by lakano** [comment]
Same as @xXSalamanderXx , impossible to open even from Terminal : 
```
 ~ $ flatpak run com.vscodium.codium
com.vscodium.codium-wrapper: Setting up NPM packages
com.vscodium.codium-wrapper: Setting up Cargo packages
com.vscodium.codium-wrapper: Setting up Python packages
com.vscodium.codium-wrapper: Setting up Ruby packages

 ~ $ 

```
I'm under Arch Linux (up to date), Linux 6.15.4-zen2-1-zen, Gnome 48, Wayland

**Comment by lakano** [comment]
A workaround for those impacted is to revert to the previous commit like this : 
`flatpak update --user --commit=3d41eb090a8674dc04ef6a607e4baed8d540acb7b8da27dc747854f4a3d15fe9 com.vscodium.codium
`
This will install the v1.101.03933 of the 14th June
The last version v1.101.24242 doesn't works at all for me.

**Comment by x80486** [comment]
Why don't you instead upgrade since this issue is already fixed.

**Comment by lakano** [comment]
@x80486 As explained, I was using the last upgraded version ( 1.101.24242 of yesterday ) available from Flathub. This last version doesn't works. I've reverted to the previous one ( v1.101.03933 of the 14th June), to permit to launch it.

**Comment by x80486** [comment]
I don't want to clutter the thread, but I'm using a similar configuration and haven't encountered that issue again.

```shell
                  -`                     x80486@uplink
                 .o+`                    -------------
                `ooo/                    OS: Arch Linux x86_64
               `+oooo:                   Kernel: Linux 6.12.35-1-lts
              `+oooooo:                  Uptime: 52 mins
              -+oooooo+:                 Packages: 614 (pacman), 89 (flatpak)
            `/:-:++oooo+:                Shell: bash 5.2.37
           `/++++/+++++++:               Display (Dell Inc. 24"): 1920x1080 @ 60 Hz in 24" [External]
          `/++++++++++++++:              DE: GNOME 48.3
         `/+++ooooooooooooo/`            WM: Mutter (Wayland)
        ./ooosssso++osssssso+`           WM Theme: Adwaita
       .oossssso-````/ossssss+`          Theme: Adwaita [GTK2/3/4]
      -osssssso.      :ssssssso.         Icons: Adwaita [GTK2/3/4]
     :osssssss/        osssso+++.        Font: Ubuntu Regular (11pt) [GTK2/3/4]
    /ossssssss/        +ssssooo/-        Cursor: Adwaita (24px)
  `/ossssso+/:-        -:/+osssso+-      Terminal: GNOME Console 48.0.1
 `+sso+:-`                 `.-/+oso:     Terminal Font: Ubuntu Mono Regular (13pt)
`++:.                           `-/+/    CPU: Intel(R) Core(TM) i7-8700 (12) @ 4.60 GHz
.`                                 `/    GPU: Intel UHD Graphics 630 @ 1.20 GHz [Integrated]
                                         Memory: 8.54 GiB / 31.03 GiB (28%)
                                         Swap: 0 B / 32.00 GiB (0%)
                                         Disk (/): 203.00 GiB / 914.34 GiB (22%) - ext4
                                         Local IP (wlp4s0): 192.168.*.*/24
                                         Locale: en_US.UTF-8
```

You might want to reset the application permissions or check if there's anything open in VSCodium related to this. 

The issue seems to be more specific now. I've tried several times but can't reproduce it — and even restarted to check 😅

**Comment by lakano** [comment]
@x80486 Doing a reset permission and double check there is no ~/.local/share/flapak/override was my 1st reaction, but the bug was still present, even after a reboot.
To make new tests, I've upgraded to the last non-working version on my host.
Then with the verbose option I've noticed a problem with the SDK of freedesktop

```
$ flatpak run -v com.vscodium.codium
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/guillaume/.local/share/flatpak
F: Opening user flatpak installation at path /home/guillaume/.local/share/flatpak
F: Opening user flatpak installation at path /home/guillaume/.local/share/flatpak
F: /home/guillaume/.local/share/flatpak/runtime/org.freedesktop.Sdk/x86_64/24.08/e8d0498c71f98949d7fb0ff0513bbba44c006005f9f1dcc89d6eb023308b4247/files/lib32 does not exist
F: Cleaning up unused container id 2423590879
F: Cleaning up per-app-ID state for com.vscodium.codium
F: Cleaning up unused container id 2311361542
F: Cleaning up per-app-ID state for com.vscodium.codium
F: Allocated instance id 2375185103
F: Add defaults in dir /com/vscodium/codium/
F: Add locks in dir /com/vscodium/codium/
F: Allowing host-fs access
F: Allowing wayland access
F: Allowing pulseaudio access
F: Running 'bwrap --args 39 -- xdg-dbus-proxy --args=42'
F: Running 'bwrap --args 39 -- com.vscodium.codium'
com.vscodium.codium-wrapper: Setting up NPM packages
com.vscodium.codium-wrapper: Setting up Cargo packages
com.vscodium.codium-wrapper: Setting up Python packages
com.vscodium.codium-wrapper: Setting up Ruby packages
                                                         
```

« lib32 does not exist » could be may be related to this problem?

Here is my freedesktop installed packages:
```
 $ flatpak list | grep freedesktop
Freedesktop Platform	org.freedesktop.Platform	freedesktop-sdk-23.08.31	23.08	user
Freedesktop Platform	org.freedesktop.Platform	freedesktop-sdk-24.08.22	24.08	user
i386	org.freedesktop.Platform.Compat.i386		24.08	user
Mesa	org.freedesktop.Platform.GL.default	25.0.5	23.08	user
Mesa (Extra)	org.freedesktop.Platform.GL.default	25.0.5	23.08-extra	user
Mesa	org.freedesktop.Platform.GL.default	25.1.3	24.08	user
Mesa (Extra)	org.freedesktop.Platform.GL.default	25.1.3	24.08extra	user
Intel VAAPI driver	org.freedesktop.Platform.VAAPI.Intel		23.08	user
Intel VAAPI driver	org.freedesktop.Platform.VAAPI.Intel		24.08	user
FFmpeg extension with extra codecs	org.freedesktop.Platform.ffmpeg-full		24.08	user
openh264	org.freedesktop.Platform.openh264	2.5.1	2.5.1	user
Freedesktop SDK	org.freedesktop.Sdk	freedesktop-sdk-23.08.31	23.08	user
Freedesktop SDK	org.freedesktop.Sdk	freedesktop-sdk-24.08.22	24.08	user

```
